# Generated by Django 4.2.2 on 2023-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_auctionlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='actualBid',
            field=models.FloatField(default=models.FloatField()),
        ),
    ]
