# Generated by Django 4.2.2 on 2023-07-13 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlisting_lastoferrer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('oferrer', 'watchlist', 'date')},
        ),
    ]
